# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaParse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Дельты',
                'verbose_name_plural': 'Дельты',
            },
        ),
        migrations.CreateModel(
            name='GroupsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Сылка группы')),
                ('author', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
            },
        ),
        migrations.CreateModel(
            name='SearchStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_date', models.DateTimeField()),
                ('users', models.TextField()),
                ('users_count', models.CharField(max_length=200, verbose_name='количество участников')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcer.GroupsList')),
            ],
            options={
                'verbose_name': 'История проверок',
                'verbose_name_plural': 'История проверок',
            },
        ),
        migrations.AddField(
            model_name='deltaparse',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcer.GroupsList'),
        ),
    ]
