# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcer', '0002_auto_20170616_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstory',
            name='users_count',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='количество участников'),
        ),
    ]
