# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Parcer', '0003_auto_20170616_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchstory',
            name='parsing_date',
        ),
        migrations.AddField(
            model_name='searchstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
